### ISSUE TITLE
不能长时间后台运行，基本10分钟内就自动停止了，设置了省电权限配置也没用

### ISSUE THREAD

**Issue by master-yun-yun** [eritpchy/webdav-aliyundriver-android#1]
启动，转入后台运行，基本10分钟内就自动停止了，设置了省电权限配置也没用。
手机自身的设置里允许后台运行，不执行省电策略，还是会10分钟内自动停止
达人能看看什么情况吗？

**Comment by eritpchy** [comment]
安卓系统确实是有这种情况，比如内存不足， 系统原因 等等都会杀死后台应用， 如不能用建议使用其他的类型实现
