### ISSUE TITLE
限速了播放不了

### ISSUE THREAD

**Issue by yehiuew** [eritpchy/webdav-aliyundriver-android#100]
速度只有1m/s，作者能修复一下嘛

**Comment by kyleyh838** [comment]
> 

你还能有1m啊，我直接100多kb了，看个电视卡的怀疑人生，听说是接口的原因，只能等作者大大更新了

**Comment by yehiuew** [comment]
求更新

**Comment by vincentfayer** [comment]
啊，我搞了一天，原来是限速了，求作者更新

**Comment by pic5566** [comment]
电影看到一半不能看了，原来被限速，晕了，刚买的阿里会员

**Comment by 9390041** [comment]
老大,授权问题这么难搞吗?

**Comment by yehiuew** [comment]
现在完全没速度

**Comment by eritpchy** [comment]
重复issues https://github.com/eritpchy/webdav-aliyundriver-android/issues/97
