### ISSUE TITLE
播放出现问题，读取文件列表都没问题

### ISSUE THREAD

**Issue by beijinggala** [eritpchy/webdav-aliyundriver-android#103]
今天发现实使用kodi infuse都可以读取文件列表，但是无法进行文件播放，一直卡在再读取界面上，无法读取视频文件，jpg文件读取没问题

**Comment by z985690047** [comment]
被限速了

**Comment by roby411** [comment]
接口问题 等更新吧

**Comment by sandaoyan** [comment]
> 被限速了

限个毛！软件本身问题，我用clouddrive 播放100m码率也很流畅

**Comment by eritpchy** [comment]
阿里把所有没接官方内测接口的都给限速了, 咱们还没接好, 建议使用开源的alist
