### ISSUE TITLE
感谢po主分享这么好的app，不过最近是不是用不了了？

### ISSUE THREAD

**Issue by TheDustInTheAir** [eritpchy/webdav-aliyundriver-android#104]
感谢po主分享这么好的app，不过最近是不是用不了了？

挂载WebDAV之后能查看文件目录，但是任何文件的读取都不可用， 好像听说是近期阿里云盘那边做了什么调整

**Comment by wanglei-github** [comment]
em....说话的艺术，学习了，哈哈

**Comment by TheDustInTheAir** [comment]
头一阵子我都是能用的，也就是大概从2月开始用不了了， 然后网上查了一下都说是阿里云盘那边改变了什么政策所导致的。 目录全部都能看，但是文件一个打不开，一个复制不了

**Comment by eritpchy** [comment]
已更新 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/3.0.0
