### ISSUE TITLE
3.0版10分钟出炉，我就用了。

### ISSUE THREAD

**Issue by iduoe** [eritpchy/webdav-aliyundriver-android#105]
用官方api点登录，加载不出来登录界面啊？赶紧更新吧大佬

**Comment by iwinkers** [comment]
同

**Comment by eritpchy** [comment]
我似乎听他们说过这个情况，还没空测试，敢问是什么设备 系统版本号多少

**Comment by iduoe** [comment]
![Uploading Screenshot_2023-03-03-23-12-34-13_bbd33d893fa02fd5d067ad04ef32e618.jpg…]()

**Comment by iduoe** [comment]
一加8 安卓13系统 
![Screenshot_2023-03-03-23-15-29-35_912cdc8ddab0744f462b5d1cd8a86ecd](https://user-images.githubusercontent.com/117105738/222757196-33bac625-2aa2-420e-955f-2b873d8bc5aa.jpg)

**Comment by gaotianliuyun** [comment]
手机启动服务后，电脑访问提示：
HTTP ERROR 401
Problem accessing /. Reason:

    AliyunDriveAccessTokenInvalid
Powered by Jetty://

是怎么回事？

**Comment by eritpchy** [comment]
官方api必须使用程序自带的登录获取token, 已更新 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/3.0.1

**Comment by iduoe** [comment]
牛牛牛
