### ISSUE TITLE
3.0版本点击登录阿里云盘打不开页面

### ISSUE THREAD

**Issue by z985690047** [eritpchy/webdav-aliyundriver-android#106]
发现地址是个192.168.50.86的ip
![Screenshot_2023-03-03-23-13-39-61_bbd33d893fa02fd5d067ad04ef32e618](https://user-images.githubusercontent.com/34087893/222756577-776efac3-bf2d-4038-a7c7-63a46895bce8.jpg)

**Comment by iduoe** [comment]
同样

**Comment by eritpchy** [comment]
已更新 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/3.0.1
