### ISSUE TITLE
电视安装最新版本3.0.1，弹出登录对话框，电视遥控器怎么获取焦点输入账号和密码？

### ISSUE THREAD

**Issue by amd256** [eritpchy/webdav-aliyundriver-android#107]
电视安装最新版本3.0.1，弹出登录对话框，电视遥控器怎么获取焦点输入账号和密码？

**Comment by eritpchy** [comment]
等更新

**Comment by naihe138** [comment]
+1，等更新

**Comment by eritpchy** [comment]
请查收3.0.2, 已支持扫码登录
  https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/3.0.2

**Comment by amd256** [comment]
更新3.0.2版本，可以扫码登录了，非常感谢！！！

**Comment by amd256** [comment]
nplayer播放正常
