### ISSUE TITLE
建议开发一个PC版的挂载软件，从而解决电视系统自动关闭后台的问题，谢谢！

### ISSUE THREAD

**Issue by jijie94** [eritpchy/webdav-aliyundriver-android#12]
建议开发一个PC版的挂载软件，用电脑挂载，这样可以解决电视系统自动关闭后台的问题，虽然现在PC上有CloudDrive，但是CloudDrive比较卡顿，挂载后，在电视上并不能流畅播放，希望可以尽快开发电脑版的阿里云盘挂载软件，谢谢！

**Comment by Hellogu** [comment]
PC版的可以在电脑上装个docker，然后用这个项目
https://github.com/messense/aliyundrive-webdav

**Comment by eritpchy** [comment]
这个本来就是基于pc的改的
