### ISSUE TITLE
已经更新

### ISSUE THREAD

**Issue by zqzhym** [eritpchy/webdav-aliyundriver-android#22]
作者已经更新了 但是我们要怎么用

**Comment by 6ix7evenzzz** [comment]
更新了吗

**Comment by nexusty** [comment]
还没有，希望尽快更新

**Comment by zqzhym** [comment]
> 还没有，希望尽快更新

他的代码显示几小时更新过，打包成apk就行了

**Comment by dissrr** [comment]
> 

怎么弄

**Comment by xieping5820** [comment]
打个包就行了，改了个api地址

**Comment by zqzhym** [comment]
> 打个包就行了，改了个api地址

我们能自己打包吗

**Comment by dissrr** [comment]
> 打个包就行了，改了个api地址

不会啊 麻烦你能发一下嘛

**Comment by zby4051** [comment]
怎么打包啊

**Comment by kungwhwa** [comment]
应该可以解包原来的apk, 找到这个文件修改那2行，再重新打包

**Comment by zby4051** [comment]
原来的APK解包后找不到作者发的这个文件，具体修改的文件名不知道叫什么

**Comment by nexusty** [comment]
碰到同样的问题

**Comment by Foyuki** [comment]
> 应该可以解包原来的apk, 找到这个文件修改那2行，再重新打包

不行的

**Comment by Foyuki** [comment]
求作者更新下编译好的版本

**Comment by eritpchy** [comment]
人在外头，连不上自己的电脑

**Comment by dissrr** [comment]
> 人在外头，连不上自己的电脑

大佬什么时候回家

**Comment by eritpchy** [comment]
https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/1.6.0
已经更新

**Comment by zqzhym** [comment]
> https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/1.6.0 已经更新
有bug,如果已经删了老版本 然后来装这个新版本扫码登录的时候 就会闪退

**Comment by eritpchy** [comment]
目前不能扫码

**Comment by zqzhym** [comment]
> 目前不能扫码

那有计划短期内再更新吗？还是短期内先将就用

**Comment by eritpchy** [comment]
https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/1.7.0
