### ISSUE TITLE
希望能生成新的apk文件

### ISSUE THREAD

**Issue by nexusty** [eritpchy/webdav-aliyundriver-android#24]
希望大神能帮忙生成新的apk文件，谢谢了，更新下refresh token的代码

**Comment by 6ix7evenzzz** [comment]
+1

**Comment by huancuiqu** [comment]
都在等待

**Comment by mackon666** [comment]
同求啊。

**Comment by eritpchy** [comment]
https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/1.6.0
已经更新

**Comment by dissrr** [comment]
> https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/1.6.0
> 已经更新

过年了🧨 感谢🙏

**Comment by yubel1009** [comment]
> https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/1.6.0
> 已经更新

感谢感谢 作者辛苦了
