### ISSUE TITLE
1.6扫码后，点关闭闪退，请帮忙修复，谢谢了

### ISSUE THREAD

**Issue by heny8643** [eritpchy/webdav-aliyundriver-android#27]
1.6扫码后，点关闭闪退，请帮忙修复，谢谢了

**Comment by ata5028** [comment]
没错，更新了安卓版1.6，还是会闪退

**Comment by jijie94** [comment]
是的，我也会闪退

**Comment by eritpchy** [comment]
https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/1.7.0
