### ISSUE TITLE
1.6版本依旧有问题

### ISSUE THREAD

**Issue by xieping5820** [eritpchy/webdav-aliyundriver-android#31]

**Comment by xieping5820** [comment]
可能是阿里更改了token刷新机制?

**Comment by xieping5820** [comment]
token问题

**Comment by xlcoffee** [comment]
yes

**Comment by WYbili** [comment]
在三星C9pro上扫完码就会闪退，显示持续停止。安卓版本为8.0。求修复。
After scanning the code on the Samsung C9pro it flashes back and shows persistent stop.The Android System version is 8.0.0.Looking for a fix. Thanks.

**Comment by eritpchy** [comment]
https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/1.7.0
