### ISSUE TITLE
阿里云webdav突然连接不上了

### ISSUE THREAD

**Issue by rjn0815** [eritpchy/webdav-aliyundriver-android#38]
之前可以连接看视频，昨晚播放视频时突然断线，接着就连接不上了，重装电视端kodi，重装阿里webdav，换网盘账号都试过了，还是不行，请大佬帮忙看看是什么问题
![Screenshot_20220819-004229_Webdav](https://user-images.githubusercontent.com/111525601/185449497-125b7175-d11f-4081-b78a-2f5829202dfd.jpg)

**Comment by huancuiqu** [comment]
确实不好用了，怎么回事呢？
