### ISSUE TITLE
第二天打开不能用了，重新下载也不行，手机是华为

### ISSUE THREAD

**Issue by 1048036463** [eritpchy/webdav-aliyundriver-android#4]
![fdcf9aadb508bf2fb6d0eb84036ea1cc](https://user-images.githubusercontent.com/57879914/157405916-1b4e7456-3a6c-4962-ba32-2edc838f2fe4.jpg)

**Comment by lanzi99** [comment]
我也有这个情况不知咋解决

**Comment by eritpchy** [comment]
更新试试
