### ISSUE TITLE
java.io.InterruptedIOException: interrupted

### ISSUE THREAD

**Issue by singer1026** [eritpchy/webdav-aliyundriver-android#40]
后台运行了一段时间后大概3分钟左右 服务就自动停止了
设备 当贝B3Pro 
安卓版本 Android9
固件版本 3.1.2.1
桌面版本 1.6.0
![tempImage5QPLTe](https://user-images.githubusercontent.com/4211735/186902859-60ca2c83-ff91-47fd-95ff-90611c1780bb.gif)
![tempImageKPgyGd](https://user-images.githubusercontent.com/4211735/186902974-6c5a3584-39f5-46f5-9ab2-2f53fe7460c5.gif)

**Comment by eritpchy** [comment]
杀后台无解
