### ISSUE TITLE
Amlogic T972 CPU投影仪，卡顿严重

### ISSUE THREAD

**Issue by LucasPKU** [eritpchy/webdav-aliyundriver-android#41]
只开webdav和kodi，卡顿非常严重，经常报流大卡顿提示，正常么- -

**Comment by LucasPKU** [comment]
找到问题了，webdav安装到投影仪后，ip为投影仪本机，kodi添加源后会自动识别为读取本机视频，因此不会添加缓存（逻辑上本机视频确实不需要缓存，咋设置都没缓存），所以一直实时读取，造成卡顿严重。作者或大家有解决方案么？我现在是挂在局域网内安卓机实现的。

**Comment by eritpchy** [comment]
进xml吧kodi的缓存打开
