### ISSUE TITLE
希望可以在quest2 vr设备上运行

### ISSUE THREAD

**Issue by MetaQuest2** [eritpchy/webdav-aliyundriver-android#57]
pico3-4可以运行，但是quest平台不可以运行，我测试了1.0版本可以运行，但是无法扫码添加阿里云，输入数字后也无法添加，希望作者可以在后续版本支持quest平台，因为你这个程序真的太香啦。

**Comment by eritpchy** [comment]
啥玩意, 我需要怎么测试这个平台?
