### ISSUE TITLE
大佬，希望能搞个纯webDav挂载到本地的东西。

### ISSUE THREAD

**Issue by stonyme** [eritpchy/webdav-aliyundriver-android#58]
如题，我已经有alist挂载了各个网盘，想吧webdav挂载到手机本地，然后emby加载。可是找了好久都找不到能实现这个功能的，有幸看到大佬的这个项目，只是这个项目只能用户阿里云的。能不能搞个简化版的自己输入webdav服务地址，用户名和密码，路径的。这样的话就太好了。我找了几个都只能在文件管理器里看到，emby都无法识别的。只有大佬你的能挂到安卓本地目录。

**Comment by eritpchy** [comment]
你需要的是rclone

**Comment by stonyme** [comment]
> 

rclone没有安卓端吧

**Comment by eritpchy** [comment]
有的 https://github.com/eritpchy/rclone-mount-magisk
