### ISSUE TITLE
无法运行Webdav

### ISSUE THREAD

**Issue by Jack1sight** [eritpchy/webdav-aliyundriver-android#59]
下载了最新apk，还是无法运行。![mmexport1673254121126.jpg](https://user-images.githubusercontent.com/96098061/211270028-173e95c8-c0ce-4ba0-96a8-2f001a774ea1.jpg)

**Comment by sunzhe1234** [comment]
你不是一个人

**Comment by bzzb212** [comment]
我也遇见了这个问题

**Comment by BrynnHy** [comment]
俺也一样

**Comment by windstander** [comment]
作者啊，这个软件为什么还要内置一个过期功能。
