### ISSUE TITLE
提示更新但没有新版本发布

### ISSUE THREAD

**Issue by MammonLess** [eritpchy/webdav-aliyundriver-android#61]
弹窗要求更新，点击“检查更新”是最新版本，来到更新网址也是最新版本，重新下载安装还是弹窗提示，弹窗无法关闭，点击“确定”会直接退出软件。

**Comment by lv65-max** [comment]
刚刚发现了，解决了没有？

**Comment by BrynnHy** [comment]
我也是这样，检测更新提示已经是最新版本了，估计需要作者大佬解决了

**Comment by tomdegnan** [comment]
我也遇到了

**Comment by Hoshino324** [comment]
一样，不过之前设置好的还在正常运行，就留着弹窗在那不点，我这里infuse还可以正常加载

**Comment by nicyau** [comment]
+1

**Comment by nicyau** [comment]
+1

**Comment by xun-zhang-9** [comment]
加一，本来不管弹窗可以运行，手欠卸载重装还是不行

**Comment by windstander** [comment]
附议

**Comment by zangqiyue** [comment]
+1

**Comment by Jack1sight** [comment]
附议

**Comment by KamenRevice** [comment]
![Screenshot_2023-01-10-16-02-12-246_net xdow webdavaliyundriver](https://user-images.githubusercontent.com/36665957/211495040-884ea8fd-a399-495d-8cf9-409f7605490e.jpg)
附议，如何解决，是bug吗

**Comment by Hoshino324** [comment]
现在提示refresh token也过期了…被弹窗挡着还没法进去手动刷新，算是彻底废了

**Comment by BEIABEF** [comment]
> 现在提示refresh token也过期了…被弹窗挡着还没有法进去手动刷新，算完蛋了

有root可以用mt进入data改动，就是现在用kodi视频也会卡了，估计阿里搞的，我今天换了几个refresh了，估计这个方案用不了多久了

**Comment by wruta99** [comment]
> 

请教下mt是啥

**Comment by BEIABEF** [comment]
> > 
> 
> mt是啥

Mt管理器

**Comment by lv65-max** [comment]
没有删除重装，没有理会弹窗直接后台的，不过过段时间最下方就提示服务已启动，我用的电视盒子，不知道还能用多久

**Comment by Hoshino324** [comment]
> 

我倒是没root…不过刚才突发奇想，覆盖安装了下1.6版本…还是提示更新，但是自动更新refresh roken正常工作了，神奇

**Comment by ysinx** [comment]
+1

**Comment by Caligari999** [comment]
俺也一样
