### ISSUE TITLE
无法使用的解决办法√√√√√√

### ISSUE THREAD

**Issue by minesdaw** [eritpchy/webdav-aliyundriver-android#62]
# 无法使用解决办法
手机要root，并且有LSPosed 框架，安装对话框取消模块即可。（懂得都懂）

不明白的留言，不会的人多了，我好好写个教程。

**Comment by SuperTominWild** [comment]
算了，我说个简单的办法吧，希望不要影响Eritpchy的本意。

不用Root，你把安卓系统时间改成2023年1月10号之前就能打开了。然后设置好自己的Token以及程序自启动。这样你改回系统时间后，点击程序虽然会有提示，但是后台已经在运行了。

另外作者已经放了很充分的资料了。

**Comment by Real-Dalao** [comment]
改系统时间到2023年1月10号之前有用，如果是跟我一样安装在安卓电视上的话可以直接不改回来，又不拿电视看时间

**Comment by naihe138** [comment]
> 改系统时间到2023年1月10号之前有用，如果是跟我一样安装在安卓电视上的话可以直接不改回来，又不拿电视看时间

+1，我的电视也好了

**Comment by yoyodadada** [comment]
我的盒子改不了时间。。。。

**Comment by ngomg666** [comment]
改了时间现在看10分钟就弹出去了😭

**Comment by Real-Dalao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    什么弹出去了？如果是这个软件的话你是不是卸载重装过，然后忘了关电源优化，被杀后台了。
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年1月12日 21:08
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [eritpchy/webdav-aliyundriver-android] 无法使用的解决办法√√√√√√ (Issue #62)
        
      
    
  
  

改了时间现在看10分钟就弹出去了😭

**Comment by ngomg666** [comment]
没杀后台，电源优化都关了，现在看4k视频，隔10分钟左右会提示服务已启动，然后就退出播放了，得重新播放，看1080p的也会提示服务已启动，但是不会弹出去

**Comment by Real-Dalao** [comment]
那是不是你播放器的问题呀，我用kodi也是过一会显示一次服务已启动，但是没弹出。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月12日(周四) 晚上9:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [eritpchy/webdav-aliyundriver-android] 无法使用的解决办法√√√√√√ (Issue #62)




 
没杀后台，电源优化都关了，现在看4k视频，隔10分钟左右会提示服务已启动，然后就退出播放了，得重新播放，看1080p的也会提示服务已启动，但是不会弹出去

**Comment by ngomg666** [comment]
> 那是不是你播放器的问题呀，我用kodi也是过一会显示一次服务已启动，但是没弹出。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年1月12日(周四) 晚上9:50 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [eritpchy/webdav-aliyundriver-android] 无法使用的解决办法√√√√√√ (Issue #62) 没杀后台，电源优化都关了，现在看4k视频，隔10分钟左右会提示服务已启动，然后就退出播放了，得重新播放，看1080p的也会提示服务已启动，但是不会弹出去 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
1G一集的电视剧不会弹出，十几个G一集的电视剧会弹出😥给我整不会了

**Comment by ngomg666** [comment]
> 那是不是你播放器的问题呀，我用kodi也是过一会显示一次服务已启动，但是没弹出。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年1月12日(周四) 晚上9:50 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [eritpchy/webdav-aliyundriver-android] 无法使用的解决办法√√√√√√ (Issue #62) 没杀后台，电源优化都关了，现在看4k视频，隔10分钟左右会提示服务已启动，然后就退出播放了，得重新播放，看1080p的也会提示服务已启动，但是不会弹出去 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

1G一集的电视剧不会弹出，十几个G一集的电视剧会弹出😥给我整不会了

**Comment by roby411** [comment]
作者已经更新了
