### ISSUE TITLE
本项目怎么做到手机挂载流量跑在手机上的?x

### ISSUE THREAD

**Issue by linxiaolulu** [eritpchy/webdav-aliyundriver-android#63]

**Comment by linxiaolulu** [comment]
试过用软路由上的阿里webdav 但是流量只能跑在电视上，一些4k电影播放不流畅受阻于电视的百兆网卡，而本项目手机挂载后电视观看流畅，手机负责跑流量。

**Comment by i990049** [comment]
多大的事，买个安卓机顶盒不就完了，我连手机都不用，直接装机顶盒上面用nplayer和kodi看，切换音轨放软字幕方便多了

**Comment by eritpchy** [comment]
和其他的挂载一样
