### ISSUE TITLE
芝杜Z9S安装的1.80版本，无法成功挂载阿里云

### ISSUE THREAD

**Issue by malimaxiu** [eritpchy/webdav-aliyundriver-android#66]
我是用芝杜Z9S安装的1.80版本，Z9S 是安卓7.1 ，软件可以运行，但用webdav挂载的阿里云盘却无法调用 阿里云webdav 1.80这个软件，显示连接失败，应该是软件兼容问题，希望作者能够更新一下。

**Comment by lv65-max** [comment]
海美迪也不能用，改回之前的版本了。

**Comment by malimaxiu** [comment]
是切出去，软件直接就关闭了，不是系统杀掉进程，好像是软件自己就关闭了

**Comment by hk-style** [comment]
The method 'java.lang.String java.lang.Object.toString()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'net.sf.webdav.methods.f' appears in /data/data/net.xdow.webdavaliyundriver/cache/jetty-0.0.0.0-8080-ROOT.war--any-/webinf/WEB-INF/lib/classes.dex)

**Comment by eritpchy** [comment]
是的, 切出去就被系统杀掉了
