### ISSUE TITLE
更新1.8后无法使用

### ISSUE THREAD

**Issue by imaqine** [eritpchy/webdav-aliyundriver-android#68]
显示找不到服务器
The method 'java.lang.String java.lang.Object.toString()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'net.sf.webdav.methods.f' appears in /data/data/net.xdow.webdavaliyundriver/cache/jetty-0.0.0.0-8080-ROOT.war--any-/webinf/WEB-INF/lib/classes.dex)

**Comment by hk-style** [comment]
一样的问题

**Comment by xiaoma70513** [comment]
我也是，不知道该怎么办

**Comment by eritpchy** [comment]
卸载重装
