### ISSUE TITLE
1.8我也用不了。但安卓有一款 小白云盘。功能与webdav差不多，更好用些。直接调用kodi，源码画质音轨，

### ISSUE THREAD

**Issue by sandaoyan** [eritpchy/webdav-aliyundriver-android#70]
1.8我也用不了。但安卓有一款 小白云盘。功能与webdav差不多，更好用些。直接调用kodi，源码输出画质音轨，

**Comment by malimaxiu** [comment]
小白云盘 音轨是假直通

**Comment by KamenRevice** [comment]
小白云盘哪里下载，开源嘛

**Comment by tomdegnan** [comment]
完全不一样啊，小白都不能挂webdav

**Comment by sandaoyan** [comment]
> 

不需要挂载，可以把它看做阿里云盘，打开就能用。

**Comment by sandaoyan** [comment]
> 小白云盘 音轨是假直通

这个小白是前几天刚出来的，不是以前的。用默认播放器只有2声道。用kodi就是源码。

**Comment by sandaoyan** [comment]
> 小白云盘哪里下载，开源嘛

恩山论坛

**Comment by i990049** [comment]
小白云盘放软字幕超级大，安装包也膨胀到几十M，让后阿里云盘官方TV版也出来了，既然官方都有了，那些第三方的肯不肯继续更新就看作者心情了，每次阿里换端口都要死一批第三方软件。

**Comment by rhehdd** [comment]
阿里云盘tv版也行

**Comment by i990049** [comment]
> 阿里云盘tv版也行

一样不能切换音轨和字幕，而且功能比小白云盘还弱，4:3视频全部拉伸成16:9比例，人物都变成了胖子，难看死了，还不能加载同一个文件夹的外挂字幕
