### ISSUE TITLE
用不了的小伙版可以试试 115小幸运 Alist挂载

### ISSUE THREAD

**Issue by tomdegnan** [eritpchy/webdav-aliyundriver-android#72]

**Comment by tomdegnan** [comment]
比这个软件好用一点

**Comment by malimaxiu** [comment]
安卓版本 有教程吗？好实现吗？

**Comment by i990049** [comment]
必须要安卓7才能用，我的机顶盒不支持

**Comment by tomdegnan** [comment]
教程  https://www.52pojie.cn/thread-1722781-1-1.html

**Comment by i990049** [comment]
> 教程 https://www.52pojie.cn/thread-1722781-1-1.html

小幸运要求安卓7，我的机顶盒是安卓6，用不了

**Comment by rhehdd** [comment]
我已经用手机软件termux搭了一个alist

**Comment by i990049** [comment]
> 我已经用手机软件termux搭了一个alist

这个都能不能在机顶盒后台运行？现在说1.8.0版用不了的都是机顶盒用户

**Comment by malimaxiu** [comment]
机顶盒 用不少

**Comment by malimaxiu** [comment]
用不了

**Comment by sandaoyan** [comment]
> 用不了
盒子可以用的。多看看教程

**Comment by algz** [comment]
1.8版本，kodi连不上，盒子和手机安卓都不行。
