### ISSUE TITLE
115小幸运装在安卓盒子里，然后用kodi挂载

### ISSUE THREAD

**Issue by sandaoyan** [eritpchy/webdav-aliyundriver-android#73]
实测安卓版kodi与coreelec都可以挂载。唯一遗憾是播放高码率视频卡顿。比如50-100m/s的视频。不过也很好用了，高码率的看的不多！还有一个bug是更新云盘内容，115小幸运无法实时更新，需要重新打开。

**Comment by i990049** [comment]
那是你的HDMI铜线的问题，要四根芯的才行，115小幸运要求至少安卓7才能使用，我的机顶盒是安卓6 32位用不了

**Comment by sandaoyan** [comment]
> 那是你的HDMI铜线的问题，要四根芯的才行，115小幸运要求至少安卓7才能使用，我的机顶盒是安卓6 32位用不了

hdmi线没问题。我用小白云盘调用kodi可以流畅播放源码高码率。用115挂载的话kodi和N1 coreelec都会卡顿

**Comment by i990049** [comment]
> > 那是你的HDMI铜线的问题，要四根芯的才行，115小幸运要求至少安卓7才能使用，我的机顶盒是安卓6 32位用不了
> 
> hdmi线没问题。我用小白云盘调用kodi可以流畅播放源码高码率。用115挂载的话kodi和N1 coreelec都会卡顿

你自己都说了用小白云播放高码率，高码率不等于原盘，115官方的大屏版也不是播放原盘码率，alist是原盘码率

**Comment by sandaoyan** [comment]
> > > 那是你的HDMI铜线的问题，要四根芯的才行，115小幸运要求至少安卓7才能使用，我的机顶盒是安卓6 32位用不了
> > 
> > 
> > hdmi线没问题。我用小白云盘调用kodi可以流畅播放源码高码率。用115挂载的话kodi和N1 coreelec都会卡顿
> 
> 你自己都说了用小白云播放高码率，高码率不等于原盘，115官方的大屏版也不是播放原盘码率，alist是原盘码率

这么说吧，以前 阿里云盘webdav这个软件还能用时，播放100m/s视频不卡。

**Comment by i990049** [comment]
> > > > 那是你的HDMI铜线的问题，要四根芯的才行，115小幸运要求至少安卓7才能使用，我的机顶盒是安卓6 32位用不了
> > > 
> > > 
> > > hdmi线没问题。我用小白云盘调用kodi可以流畅播放源码高码率。用115挂载的话kodi和N1 coreelec都会卡顿
> > 
> > 
> > 你自己都说了用小白云播放高码率，高码率不等于原盘，115官方的大屏版也不是播放原盘码率，alist是原盘码率
> 
> 这么说吧，以前 阿里云盘webdav这个软件还能用时，播放100m/s视频不卡。

现在阿里非会员早限速了

**Comment by sandaoyan** [comment]
> 



> > > > > 那是你的HDMI铜线的问题，要四根芯的才行，115小幸运要求至少安卓7才能使用，我的机顶盒是安卓6 32位用不了
> > > > 
> > > > 
> > > > hdmi线没问题。我用小白云盘调用kodi可以流畅播放源码高码率。用115挂载的话kodi和N1 coreelec都会卡顿
> > > 
> > > 
> > > 你自己都说了用小白云播放高码率，高码率不等于原盘，115官方的大屏版也不是播放原盘码率，alist是原盘码率
> > 
> > 
> > 这么说吧，以前 阿里云盘webdav这个软件还能用时，播放100m/s视频不卡。
> 
> 现在阿里非会员早限速了

webdav alist 不受阿里限速影响

**Comment by i990049** [comment]
> > 
> 
> > > > > > 那是你的HDMI铜线的问题，要四根芯的才行，115小幸运要求至少安卓7才能使用，我的机顶盒是安卓6 32位用不了
> > > > > 
> > > > > 
> > > > > hdmi线没问题。我用小白云盘调用kodi可以流畅播放源码高码率。用115挂载的话kodi和N1 coreelec都会卡顿
> > > > 
> > > > 
> > > > 你自己都说了用小白云播放高码率，高码率不等于原盘，115官方的大屏版也不是播放原盘码率，alist是原盘码率
> > > 
> > > 
> > > 这么说吧，以前 阿里云盘webdav这个软件还能用时，播放100m/s视频不卡。
> > 
> > 
> > 现在阿里非会员早限速了
> 
> webdav alist 不受阿里限速影响

115就算开了会员用alist也会限速，毕竟人家服务器没那么多宽带

**Comment by eritpchy** [comment]
???
