### ISSUE TITLE
2.02版本，Infuse连接显示（HTTP 错误 500）

### ISSUE THREAD

**Issue by Bkanc** [eritpchy/webdav-aliyundriver-android#86]
IP，账号密码，端口，填写的都没问题

但Infuse无法连接，显示http错误500

webdav版本2.0.2

安卓版本5.1，未root

以前1.7.0可用，从1.8.0后开始无法使用

烦请大神帮排查一下，是哪里的原因

![01](https://user-images.githubusercontent.com/125037594/219417786-7fed9996-b381-4f40-b43b-7a29d2bfb6b1.jpg)

![02](https://user-images.githubusercontent.com/125037594/219418063-16e7f94f-1007-4c5c-ab73-73cad84aeebb.png)

**Comment by Lihbo88** [comment]
我的昨天开始也是这个错误，难道是封禁了？

**Comment by Bkanc** [comment]
不知道是哪里出了问题，求大佬解惑
![03](https://user-images.githubusercontent.com/125037594/219729065-c44841ff-7e7f-4dfc-a387-010c6c42060e.png)
![04](https://user-images.githubusercontent.com/125037594/219729102-a2990dae-8bcb-4771-9ffd-4b3daa613860.jpg)

**Comment by Bkanc** [comment]
> 我的昨天开始也是这个错误，难道是封禁了？

应该还没封

**Comment by z793242777** [comment]
我看了日志，电视用kodi，请求失败，但是iPad用infuse正常
20:170
阿里云盘Webdav
.NTT8GFjMVt5SKd59qHhCmvDw5&x-oss-additional-headers=referer
&x-oss-expires=1676823401&x-oss-signature=StlA9el4Bi
%2BehftEhX6jydoAJ%2FZhOnvX8fitBJ6N19Y%3D&x-oss-signature-version=OSS2","internal_url":"http://ccp-bj29-bj-1592982087.0ss-cn-beijing-internal.aliyuncs.com/oZwut4dp%2F77318683
%2F63c40f63aab9a3cc00604cfc90c5a59c5c78c8f7
%2F63c40f632af09c01dc8249ef97afb41af8fd710b?di=bj29&dr=781700680&f=63e2258584c07d167c1648f885a0109d23b8e1da&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27EP02.mp4&security-token=CAIS
%2BgF1q6Ft5B2yfSjIr5WEKsCBhL4Q
%2B5ayW2TZlTYHb7p4gb3bmzz2IHFPeHJrBeAYt
%2FoxmW1X5vwSlq5rR4QAXlDfNVSsbXjYqVHPWZHlnuDox55m4cTX
NAr%2Blhr%2F29CoEledZdjBe%2FCrRknZnytou9XTfimjWFrXWv
%2Fgy%2BQQDLltUxK
%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpf
FtkGF1GeXkLFF%2B97DRbG
%2FdNRpMZtFVNO44fd7bKKpOlQLukMWr
%2Fwq3Pldp2ma447NWQlLnzyCMvvJ9OVDFyNOaKEnH7J%2Bq
%2FzxhTPrMnpkSlacGoABL3YitZFnhrQdllpcA2QIkzNX8pA
%2FRzNtYPbL9upBVoMnVs1FDjUIKn2p3YH4N7rmYGqyiH4A9HbPrHdJ MOs1uTNLehfo9z5phMfMu62ooVbAivc327nQxD1ShBjylJXRYnxCYyqK Y62I%2BFmlQ3OymjClMcban25BdJ%2FA6syPOhQ%3D&u=
5b5d99e9ad094944b4aa436beb2dda6d&x-oss-access-key-id=STS.NV1az5ia1LTYYBhq6Rc5Tnxpy&x-oss-additional-headers=referer&x-oss-expires=1676823401&x-oss-signature=
WTKVbws8kOO7rrFR6j5ul8DR%2BU6631e8Yr1ANp%2BrTdg%3D&x
-oss-signature-version=OSS2","cdn_url":"https://files-cdn
.aliyundrive.com/oZwut4dp%2F77318683
%2F63c40f63aab9a3cc00604cfc90c5a59c5c78c8f7
%2F63c40f632af09c01dc8249ef97afb41af8fd710b?auth_key=
1676823401-0-5b5d99e9ad094944b4aa436beb2dda6d
-e9f2cbb11d39011baff0c3cbb4022a7c&di=bj29&dr=781700680&f=63e2258584c07d167c1648f885a0109d23b8e1da&referer=https%3A%2F%2Fwww.aliyundrive.com%2F&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27EP02.mp4&u=5b5d99e9ad094944b4aa436beb2dda6d","expiration":"2023-02
-19T16:16:41.873Z","size":5482917621,"crc64 _hash":
"14973590****************86770410","content_hash":
"763864B9****************9C254E00","content_hash_name":"shal"}
20:17:29 AliYunDriverClient请求失败,
url=https://api.aliyundrive.com/users/v1/users/device/renew_session,
code=400,
body={"code":"DeviceSe**
session signature
**elnvalid","message":"device
error","requestld":"ffOfc354-cc6b-435d-9201-9048ec44598f,
0a0080e316768090495692056e84c1"}
20:17:29 AliYunDriverClientpost
https://api.aliyundrive.com/users/v1/users/device/create_session,body {"modelName":"Windows网页版"，"deviceName"："Edge浏览器"，"pubKey":"048cC143*********
*****36a033c6"}, code 200 res
{"result":true,"success":true,"code":null,"message":null}

**Comment by eritpchy** [comment]
https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.4 试试

**Comment by z793242777** [comment]
> 

现在在kodi里可以预览封面了，但还是放不出来，一直转圈圈，日志如下
20:41:00 AliYunDriverClientpost /file/get_download_url, body
{"drive_id":"781700680","expire_sec":14400,"file_id":"63e22585******
**********1c9dd4f3"}, code 200 res
{"domain_id":"bj29","drive_id":"781700680","file_id":
/'63e22585****************1c9dd4f3","revision id"·
'63e22585****************dbff0146"."method":"GET"."ur["·"https://cn
-beijing-data.aliyundrive.net/6mDbdl97%2F587064631
%2F63ddc2ceba6c7eb7f0e44fceab061e2b4a4be7a6
%2F63ddc2ce71d995536d864e7ebba11ca597f2899e?di=bj29&dr=781700680&f=63e22585189a8fbb4150463c8a8bc6c41c9dd4f3&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27EP21.mp4&security-token=CAIS
%2BgF1q6Ft5B2yfSjIr5fPMfL8rJ1ggJS9VWWIkkMEWetnqbTdtjzZIHFP
eHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNX
%2FLX3jYqVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEledZdjBe
%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLltUxK
%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpf
FtkGF1GeXkLFF%2B97DRbG
%2FdNRpMZtFVNO44fd7bKKpOlQLukMWr
%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyNOaKEnH7J%2Bq
%2FzxhTPrMnpkSlacGoABkMlTvyrd5u%2FfEV
%2BlQpNzq1gQ4OuRuVlWwjOLGrdSPZP
%2BeoKANR8uwoDwCwcy1ice1BmJGfpAksGclswb
%2BxpRsH4Kaq4xhNoP9ZRihLipWqTgi
%2FqGnNGTZf4M62mp9rMuytU3Dd3hmffmMwfjBVUCZJMOXz42PrH
PTrOk3/Ym9T8%3D&u=5b5d99e9ad094944b4aa436beb2dda6d&x
-oss-access-key-id=STS.NTzzHHABA7VVWC9vCQUdKFqvT&x-oss
-additional-headers=referer&x-oss-expires=1676824860&x-oss
-signature=zNaME3%2FimpPdICfCCCCUdjKwnWSazBwPcIAvWHfu%2By0%3D&x-oss-signature-version=OSS2","internal_url":"http://ccp-bj29-bj-1592982087.0ss-cn-beijing-internal.aliyuncs.com
/6mDbdl97%2F587064631
%2F63ddc2ceba6c7eb7f0e44fceab061e2b4a4be7a6
%2F63ddc2ce71d995536d864e7ebba11ca597f2899e?di=bj29&dr=7817006808f=63e22585189a8fbb4150463c8a8bc6c41c9dd4f3&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27EP21.mp4&security-token=CAIS
%2BgF1q6Ft5B2yfSjIr5fEKt%2Fbp%2BpI9KDfR17lh2g8W
%2BhHhbXttTz2IHFPeHJrBeAYt
%2FoxmW1X5vwSlq5rR4QAXlDfNUfCX3jYqVHPWZHlnuDox55m4cTX
NAr%2Blhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv
%2Fgy%2BQQDLltUxK
%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpf
FtkGF1GeXkLFF%2B97DRbG
%2FdNRpMZtFVNO44fd7bKKpOlQLukMWr
%2Fwq3Pldp2ma447NWQlLnzyCMvvJ9OVDFyNOaKEnH7J%2Bq
%2FzxhTPrMnpkSlacGoABEXiJLzHvWJaUdmtPAD976Ekk7r1FN8IAasDl
8AdQBl1BhkA8VOCOD9cgFyvnYSACE%2BNYn5YKL
%2ByMO3C3pnQkePgc29WcGVnzmsSHgsfKbqpTH%2FG9yOM
%2B3KhRYwUTTu30FZ2XQs%2FRjyX3ieU4%2FmJlDuxgC56tNa2kRMh
%2Ba%2F%2B%2Fngk%3D&u=
5b5d99e9ad094944b4aa436beb2dda6d&x-oss-access-key-id=STS
.NTqaeoJ5iCb4ExychiWgkjpFW&x-oss-additional-headers=referer&x-oss-expires=1676824860&x-oss-signature=ASP6jQOOOVnRZDZKX%2BKVThoUuXnvn1fkfrU%2FhfsihF8%3D&x-oss-signature-version=OSS2","cdn_url":"https://files-cdn.aliyundrive.com/6mDbdl97
%2F587064631%2F63ddc2ceba6c7eb7f0e44fceab061e2b4a4be7a6
%2F63ddc2ce71d995536d864e7ebba11ca597f2899e?auth_key=
1676824860-0-5b5d99e9ad094944b4aa436beb2dda6d
-87f5f329364ab7e5408b4aa39ae04bb9&di=bj29&dr=781700680&f=63e22585189a8fbb4150463c8a8bc6c41c9dd4f3&referer=https%3A%2F%2Fwww.aliyundrive.com%2F&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27EP21.mp4&u=5b5d99e9ad094944b4aa436beb2dda6d","expiration":"2023-02
-19T16:41:00.898Z","size":5716371061,"crc64_hash":
"13301230***
<**********59175132","content_hash"
"5134366C****************B7654582","content_hash_name":"sha1"}

**Comment by z793242777** [comment]
> > 
> 
> 现在在kodi里可以预览封面了，但还是放不出来，一直转圈圈，日志如下 20:41:00 AliYunDriverClientpost /file/get_download_url, body {"drive_id":"781700680","expire_sec":14400,"file_id":"63e22585****** **********1c9dd4f3"}, code 200 res {"domain_id":"bj29","drive_id":"781700680","file_id": /'63e22585****************1c9dd4f3","revision id"· '63e22585*************_**dbff0146"."method":"GET"."ur["·"https://cn -beijing-data.aliyundrive.net/6mDbdl97%2F587064631 %2F63ddc2ceba6c7eb7f0e44fceab061e2b4a4be7a6 %2F63ddc2ce71d995536d864e7ebba11ca597f2899e?di=bj29&dr=781700680&f=63e22585189a8fbb4150463c8a8bc6c41c9dd4f3&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27EP21.mp4&security-token=CAIS %2BgF1q6Ft5B2yfSjIr5fPMfL8rJ1ggJS9VWWIkkMEWetnqbTdtjzZIHFP eHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNX %2FLX3jYqVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEledZdjBe %2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLltUxK %2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpf FtkGF1GeXkLFF%2B97DRbG %2FdNRpMZtFVNO44fd7bKKpOlQLukMWr %2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyNOaKEnH7J%2Bq %2FzxhTPrMnpkSlacGoABkMlTvyrd5u%2FfEV %2BlQpNzq1gQ4OuRuVlWwjOLGrdSPZP %2BeoKANR8uwoDwCwcy1ice1BmJGfpAksGclswb %2BxpRsH4Kaq4xhNoP9ZRihLipWqTgi %2FqGnNGTZf4M62mp9rMuytU3Dd3hmffmMwfjBVUCZJMOXz42PrH PTrOk3/Ym9T8%3D&u=5b5d99e9ad094944b4aa436beb2dda6d&x -oss-access-key-id=STS.NTzzHHABA7VVWC9vCQUdKFqvT&x-oss -additional-headers=referer&x-oss-expires=1676824860&x-oss -signature=zNaME3%2FimpPdICfCCCCUdjKwnWSazBwPcIAvWHfu%2By0%3D&x-oss-signature-version=OSS2","internal_url":"http://ccp-bj29-bj-1592982087.0ss-cn-beijing-internal.aliyuncs.com /6mDbdl97%2F587064631 %2F63ddc2ceba6c7eb7f0e44fceab061e2b4a4be7a6 %2F63ddc2ce71d995536d864e7ebba11ca597f2899e?di=bj29&dr=7817006808f=63e22585189a8fbb4150463c8a8bc6c41c9dd4f3&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27EP21.mp4&security-token=CAIS %2BgF1q6Ft5B2yfSjIr5fEKt%2Fbp%2BpI9KDfR17lh2g8W %2BhHhbXttTz2IHFPeHJrBeAYt %2FoxmW1X5vwSlq5rR4QAXlDfNUfCX3jYqVHPWZHlnuDox55m4cTX NAr%2Blhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv %2Fgy%2BQQDLltUxK %2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpf FtkGF1GeXkLFF%2B97DRbG %2FdNRpMZtFVNO44fd7bKKpOlQLukMWr %2Fwq3Pldp2ma447NWQlLnzyCMvvJ9OVDFyNOaKEnH7J%2Bq %2FzxhTPrMnpkSlacGoABEXiJLzHvWJaUdmtPAD976Ekk7r1FN8IAasDl 8AdQBl1BhkA8VOCOD9cgFyvnYSACE%2BNYn5YKL %2ByMO3C3pnQkePgc29WcGVnzmsSHgsfKbqpTH%2FG9yOM %2B3KhRYwUTTu30FZ2XQs%2FRjyX3ieU4%2FmJlDuxgC56tNa2kRMh %2Ba%2F%2B%2Fngk%3D&u= 5b5d99e9ad094944b4aa436beb2dda6d&x-oss-access-key-id=STS .NTqaeoJ5iCb4ExychiWgkjpFW&x-oss-additional-headers=referer&x-oss-expires=1676824860&x-oss-signature=ASP6jQOOOVnRZDZKX%2BKVThoUuXnvn1fkfrU%2FhfsihF8%3D&x-oss-signature-version=OSS2","cdn_url":"https://files-cdn.aliyundrive.com/6mDbdl97 %2F587064631%2F63ddc2ceba6c7eb7f0e44fceab061e2b4a4be7a6 %2F63ddc2ce71d995536d864e7ebba11ca597f2899e?auth_key= 1676824860-0-5b5d99e9ad094944b4aa436beb2dda6d -87f5f329364ab7e5408b4aa39ae04bb9&di=bj29&dr=781700680&f=63e22585189a8fbb4150463c8a8bc6c41c9dd4f3&referer=https%3A%2F%2Fwww.aliyundrive.com%2F&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27EP21.mp4&u=5b5d99e9ad094944b4aa436beb2dda6d","expiration":"2023-02 -19T16:41:00.898Z","size":5716371061,"crc64_hash": "13301230**_ <**********59175132","content_hash" "5134366C****************B7654582","content_hash_name":"sha1"}

iPad端infuse正常观看

**Comment by eritpchy** [comment]
是一个资源不行还是都不行, 吧不行的文件分享出来

**Comment by z793242777** [comment]
> 是一个资源不行还是都不行, 吧不行的文件分享出来

任何一个文件都不行，小到400兆大道80g的视频都不行，我觉得是kodi出了问题，因为kodi点击一个视频以后webdav日志就卡到上面发出来那样，不再刷新，一动不动，infuse就会一直刷新滚动

**Comment by Bkanc** [comment]
> https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/2.0.4 试试

已测，2.0.4版本，iPhone端和iPad端infuse连接正常，非常感谢大佬，辛苦！

**Comment by Bkanc** [comment]
> > 是一个资源不行还是都不行, 吧不行的文件分享出来
> 
> 任何一个文件都不行，小到400兆大道80g的视频都不行，我觉得是kodi出了问题，因为kodi点击一个视频以后webdav日志就卡到上面发出来那样，不再刷新，一动不动，infuse就会一直刷新滚动

2.0.4版本，infuse可以正常连接，我觉得大概率是kodi的问题

提供个思路，不一定管用，你可以多下载几个版本的kodi试一试
