### ISSUE TITLE
日志有时候刷多了app会卡住（没开内部日志）

### ISSUE THREAD

**Issue by z985690047** [eritpchy/webdav-aliyundriver-android#92]
作者可以考虑加一个日志开关吗

**Comment by eritpchy** [comment]
1

**Comment by eritpchy** [comment]
[net.xdow.webdavaliyundriver.2.0.6.release.apk.zip](https://github.com/eritpchy/webdav-aliyundriver-android/files/10792639/net.xdow.webdavaliyundriver.2.0.6.release.apk.zip)
后台低日志版, 先更新, 免得大版本拖更太久。

**Comment by leavethink** [comment]
> [net.xdow.webdavaliyundriver.2.0.6.release.apk.zip](https://github.com/eritpchy/webdav-aliyundriver-android/files/10792639/net.xdow.webdavaliyundriver.2.0.6.release.apk.zip) 后台低日志版，先更新，免费大版拖更久。

可以 这个版本日记没那么容易卡了

**Comment by z985690047** [comment]
不卡了，太谢谢了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月23日(周四) 晚上10:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [eritpchy/webdav-aliyundriver-android] 日志有时候刷多了app会卡住（没开内部日志） (Issue #92)




  
net.xdow.webdavaliyundriver.2.0.6.release.apk.zip 后台低日志版，先更新，免费大版拖更久。
  
可以 这个版本日记没那么容易卡了
