### ISSUE TITLE
主页数据太多，软件经常卡死的问题

### ISSUE THREAD

**Issue by Bobi996** [eritpchy/webdav-aliyundriver-android#96]
主页面数据太多会经常出现卡顿或者卡死，作者可以出一个关闭运行数据显示的功能，可以更流畅运行😀

**Comment by eritpchy** [comment]
https://github.com/eritpchy/webdav-aliyundriver-android/issues/92#issuecomment-1438253407
先用着

**Comment by eritpchy** [comment]
已更新 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/3.0.0
