### ISSUE TITLE
使用后账号被限速到200k

### ISSUE THREAD

**Issue by 11jourmey** [eritpchy/webdav-aliyundriver-android#97]
怎么办这算是永久封禁了吗

**Comment by eritpchy** [comment]
没听说过 等新版

**Comment by zpccode** [comment]
没出现过，检查网络吧

**Comment by roby411** [comment]
> 没听说过 等新版

我今天用也是很卡很卡 不知道怎么回事 加载不出来

**Comment by z985690047** [comment]
我也出现这个问题了，速度一直在200KB以内，宽带网速经过测试没问题

**Comment by eritpchy** [comment]
和官方核对中.

**Comment by eritpchy** [comment]
盲猜轮到我了

**Comment by wanglei-github** [comment]
嗯？昨晚我就出现了播放视频播放不了，我用的android tv，安装了 kodi 和 咱们这个webdav，昨晚10点左右还播放80G左右的蓝光视频还没有问题，后来换了个影片，就一直不播放了，kodi一直转圈，然后进入影片后，不到1s就退出来了。
我还有个 r2s，里面也有webdav服务也是不行。

用tv测试网速没问题啊，大约下载速度有 11M/S

**Comment by eritpchy** [comment]
已更新 https://github.com/eritpchy/webdav-aliyundriver-android/releases/tag/3.0.0
